### ISSUE TITLE
Hey Paul, let me know it's really you

### ISSUE THREAD

**Issue by szegedi** [rhino/rhino.github.io#2]
I'm using this issue as a poor man's 2FA to check if I'm really being contacted by @p-bakker over Mastodon to make him co-owner of the [Mozilla Rhino google group]( https://groups.google.com/g/mozilla-rhino.) 

Paul, please leave the random token I gave you in chat as a comment here and close this issue to confirm it's you. Thanks!

**Comment by p-bakker** [comment]
gwJag4sa8R8JLTsw
